DE/urls.py
from django.contrib import admin
from task.views import home,logout_view,staff_home
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('staff_home',staff_home,name='staff_home'),

     # password reset links
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name="task/account/password_change_done.html"),name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name="task/account/password_change.html"),name='password_change'),
    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(template_name="task/account/password_reset_done.html"),name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='task/account/set_password.html'),name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='task/account/reset_password.html'),name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="task/account/password_reset_complete.html"),name='password_reset_complete'),
    path('api/v1/',include('task.api.urls')),
    path('',include('task.urls')),
    path('logout',logout_view,name='logout')

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/api/urls.py
from django.urls import path
from . import views 
from rest_framework_simplejwt.views import (
    TokenRefreshView,
)
from django.urls import re_path
from rest_framework import permissions
from django.views.generic import TemplateView
from rest_framework.schemas import get_schema_view
from .views import *
urlpatterns = [
    path('',views.getRoutes),
    path('api_schema/', get_schema_view(
        title='Task Schema',
        description='Guide for task management system api '
    ), name='api_schema'),
    path('docs/', TemplateView.as_view(
        template_name='task/docs.html',
        extra_context={'schema_url':'api_schema'}
        ), name='swagger-ui'),

    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),  
    path('apps/', AppModelListView.as_view(), name='apps'),
    path('app/<int:pk>/', AppModelDetailView.as_view(), name='app-detail'),
    
]

task/urls.py
from django.urls import path
from . import views 
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login',views.Login,name='login'),
    path('register',views.register_view,name='register'),
    path('single/<id>',views.single_view,name='single_view'),
    path('create',views.add_App,name='create'),
    path('points',views.view_points,name='points'),
    path('profile/<id>',views.view_profile,name='profile'),
    path('tasks',views.view_app_task,name='tasks'),
    path('task/<id>',views.single_task_view,name='task_view')
]

task/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models
import random as rnd
from django.db import models
import math
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save, post_delete
from datetime import timedelta, date
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager

class MyAccountManager(BaseUserManager):
    
    def create_user(self,email,username,password=None):
        if not email:
            raise ValueError("Users must have an email address.")

        if not username:
            raise ValueError("Users must have a username.")

        user =self.model(
            email=self.normalize_email(email),
            username=username
        )
        
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,email,username,password):
        user=self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user



def get_profile_image_filepath(self,filename):
    return f'profile_images/{self.pk}/{"profile_image.png"}'

def get_default_profile_image():
    return "img/avatar.png"
class Account(AbstractBaseUser):
    email =models.EmailField(verbose_name="email",max_length=60,unique=True)
    username = models.CharField(max_length=30,unique=True)
    date_joined = models.DateTimeField(verbose_name="date joined",auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    profile_image = models.ImageField(max_length=255,upload_to=get_profile_image_filepath,null=True,blank=True,default=get_default_profile_image)
    objects = MyAccountManager()

    USERNAME_FIELD ="email"
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

    def get_profile_image_filename(self):
        return str(self.profile_image)[str(self.profile_image).index('profile_images/{self.pk}/')]

    def has_perm(self,perm,obj=None):
        return self.is_admin

    def has_module_perms(self,app_Label):
        return True   




class App(models.Model):
    logo = models.ImageField()
    name = models.CharField(max_length=255)
    app_link = models.URLField()
    app_cat = models.CharField(max_length=255)
    app_subcat = models.CharField(max_length=255)
    point = models.IntegerField()
    
    
    def __str__(self):
        return self.name


class Task(models.Model):
    app = models.ForeignKey(App,on_delete=models.CASCADE)
    img = models.ImageField()
    created = models.ForeignKey(Account,on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return f" {self.created.username} task" 
        
def get_total_point(user):
    points = 0
    tasks = Task.objects.filter(created=user)
    for task in tasks:
        if task.completed:
            points += task.app.point
    return points


        

task/forms.py
from django.forms import ModelForm
from. models import *
from django import forms
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login,logout

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=255,help_text="Required . add a valid email address.")
    
    class Meta:
       model = Account
       fields = ('email','username','password1','password2')

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = Account.objects.get(email=email)
        except Exception as e:
            return email
        raise forms.ValidationError(f"Email {email} is already in use.")
    
    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            account = Account.objects.get(username=username)
        except Exception as e:
            return username
        raise forms.ValidationError(f"Username {username} is already in use.")
    
class AccountAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label="Password",widget=forms.PasswordInput)
    class Meta:
        model = Account
        fields = ("email","password")

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email,password=password):
                raise forms.ValidationError("Invalid Login")

class AppForm(ModelForm):
    class Meta:
        model = App
        fields = '__all__'
        
class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

task/api/views.py
from django.http import JsonResponse
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework_simplejwt.views import TokenObtainPairView



class MyTokenObtainPairSerializer(TokenObtainPairSerializer):
    @classmethod
    def get_token(cls, user):
        token = super().get_token(user)

        # Add custom claims
        token['username'] = user.username
        

        return token


class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer

@api_view(['GET'])
def getRoutes(request):
    routes = [
        '/api/v1/token',
        '/api/v1/token/refresh',
        '/api/v1/apps',
        
    ]
    return JsonResponse(routes,safe=False)

from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from task.models import App
from .serializers import AppModelSerializer
from .permission import ReadOnlyOrAdminPermission

class AppModelListView(generics.ListAPIView):
    queryset = App.objects.all()
    serializer_class = AppModelSerializer
    # permission_classes = [IsAuthenticated]


class AppModelDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = App.objects.all()
    serializer_class = AppModelSerializer
    permission_classes = [ReadOnlyOrAdminPermission]

task/views.py
from django.shortcuts import render
from django.contrib.auth import login, authenticate,logout
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import RegistrationForm,AccountAuthenticationForm,TaskForm
from django.contrib import messages
from .models import *
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.admin.views.decorators import staff_member_required
from .forms import *
from django.contrib import messages
import json 


# Create your views here.

@login_required(login_url='login')
def home(request):
    tasks = App.objects.all()
    return render(request,'task/home.html',{'tasks':tasks})     
    
@staff_member_required
def staff_home(request):
    tasks = App.objects.all()
    return render(request,'task/adminhome.html',{'tasks':tasks})



@staff_member_required
def add_App(request):
    form = AppForm()
    if request.method == 'POST':
        form = AppForm(request.POST, request._files)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            messages.error(request,"error occured while saving file")
            return redirect('create')
    else:
        return render(request,'task/snippets/create.html',{'form':form})
  
@login_required(login_url='login')
def single_view(request,**kwargs):
    user = request.user
    if request.method == 'POST':
        user = request.user
        print(request.POST)
        print(request.FILES)
        id = kwargs.get('id')
        app = App.objects.get(pk=id)
        new_task = Task.objects.create(app=app,img=request.FILES.get('img'),created=user,completed=False)
        new_task.save()
        try:
            print(new_task)
            return redirect('home')
        except:
            print('something went wrong')
    id = kwargs.get('id')
    print(id)
    app = App.objects.get(pk=id)
    return render(request,'task/snippets/single_task.html',{'task':app})
        

def register_view(request):
    form = RegistrationForm()

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email').lower()
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            return redirect('home')
        else:
            messages.error(request, 'An error occurred during registration')
    
    return render(request, 'task/account/register.html', {'form': form})


def Login(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        try:
            user = Account.objects.get(email=email)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Username OR password does not exit')
    return render(request, 'task/account/login.html')

@login_required(login_url='login')
def view_points(request):
    user = request.user
    tasks= Task.objects.filter(created=user)
    points = get_total_point(request.user)
    return render(request,'task/snippets/tasks.html',{'tasks':tasks,'points':points})

def logout_view(request):
    logout(request)
    return redirect("login")

@login_required(login_url='login')
def view_profile(request,**kwargs):

    id = kwargs.get('id')
    points = get_total_point(request.user)
    user = Account.objects.get(pk=id)

    return render(request,'task/snippets/profile.html',{'user':user,'points':points})

@staff_member_required
def view_app_task(request):
    tasks = Task.objects.all()
    return render(request,'task/snippets/alltasks.html',{'tasks':tasks})

@staff_member_required
def single_task_view(request,**kwargs):

    if request.method == 'POST':
        data = json.loads(request.body)
        taskId = data['taskId']
        action = data['action']
        id = taskId
        task = Task.objects.get(pk=id)
        if action == 'approve':
            task.completed = True
            task.save()
        elif action == 'disapprove':
            task.completed = False
            task.save()
        
    
    id = kwargs.get('id')
    print(id)
    task = Task.objects.get(pk=id)
    print('hello')
    return render(request,'task/snippets/single.tak.html',{'task':task})
    

task/templates/task/account/login.html
{% extends "task/base.html" %}
{% load static %}

{% block title %} 
login 
{% endblock title %}
{% block content %}
<div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
data-sidebar-position="fixed" data-header-position="fixed">
<div
  class="position-relative overflow-hidden radial-gradient min-vh-100 d-flex align-items-center justify-content-center">
  <div class="d-flex align-items-center justify-content-center w-100">
    <div class="row justify-content-center w-100">
      <div class="col-md-8 col-lg-6 col-xxl-4">
        <div class="card mb-0">
          <div class="card-body">
            <p class="text-center">Wetask</p>
            <form method='post'>
                {% csrf_token %}
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email</label>
                <input type="email" name='email' class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
              </div>
              <div class="mb-4">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" name='password' class="form-control" id="exampleInputPassword1">
              </div>
              <div class="d-flex align-items-center justify-content-between mb-4">
                <a class="text-primary fw-bold" href="{% url 'password_reset' %}">Forgot Password?</a>
              </div>
              <button class="btn btn-primary w-100 py-8 fs-4 mb-4 rounded-2" type='submit'>Sign In</button>
              <div class="d-flex align-items-center justify-content-center">
                <p class="fs-4 mb-0 fw-bold">New to Wetask?</p>
                <a class="text-primary fw-bold ms-2" href="{% url 'register' %}">Create an account</a>
              </div>
            </form>
              {% if messages %}
              {% for message in messages %}
                {% if message.tag == error %}
                <p class="text-danger">{{message}}</p>
              {% endif %}
              {% endfor %}
          {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}

task/templates/task/account/password_change.html
{% extends 'task/base.html' %}
{% load static %}
{% block content %}
<div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
data-sidebar-position="fixed" data-header-position="fixed">
<div
  class="position-relative overflow-hidden radial-gradient min-vh-100 d-flex align-items-center justify-content-center">
  <div class="d-flex align-items-center justify-content-center w-100">
    <div class="row justify-content-center w-100">
      <div class="col-md-8 col-lg-6 col-xxl-4">
        <div class="card mb-0">
          <div class="card-body">
            <h1>Password reset</h1>
            <p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>
            <form class="form-signin" method="POST"> 
                {% csrf_token %}
                <h1 class="h3 mb-3 font-weight-normal">Change password</h1>

                <div class="mb-3">
                    <label for="id_old_password" class="form-label">old password</label>
                    <input type="password" name="old_password" id="id_old_password" class="form-control" placeholder="Old password" required=true>
                </div>
                <input type="password" name="new_password1" id="id_new_password1" class="form-control" placeholder="New password" required=true>
                <input type="password" name="new_password2" id="id_new_password2" class="form-control" placeholder="Confirm password" required=true>
                {% for field in form %}
                <p> 
                    {% for error in field.errors %}
                    <p style="color:red">{{error}}</p>
                    {% endfor %}
                </p>
                {% endfor %}
    
            <input class="btn btn-primary form-control my-2" type="submit" value="Update" id="id_submit_btn">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

{% endblock content%}

task/templates/task/account/password_change_done.html
{% extends 'base.html' %}
{% load static %}
{% block content %}    
   <main id="main" class="main">
        <div class="container">
            <div class="d-flex flex-column">
                <p class="m-auto"> Your password has been Updated</p>
            </div>
        </div>
        
    </main>  
{% endblock content %} 

task/templates/task/account/password_reset_complete.html
{% extends 'task/base.html' %}
{% load static %}

{% block content%}
<div class="container">
    <div class="d-flex flex-column">
        <p class="m-auto"> Your password has been reset, you can go ahead and <a href="{% url 'login' %}">sign in</a> now.</p>
    </div>
</div>

{% endblock content%}

task/templates/task/account/password_reset_done.html
{% load static %}


{% block content %}
<div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
data-sidebar-position="fixed" data-header-position="fixed">
<div
  class="position-relative overflow-hidden radial-gradient min-vh-100 d-flex align-items-center justify-content-center">
  <div class="d-flex align-items-center justify-content-center w-100">
    <div class="row justify-content-center w-100">
      <div class="col-md-8 col-lg-6 col-xxl-4">
        <div class="card mb-0">
          <div class="card-body">
            <div class="container">
                <div class="d-flex flex-column">
                    <p class="m-auto p-2">we've emailed you instructions for setting your password, if an account exists 
                        with the email you entered.
                       You should recieve them shortly. </p>
                    <p class="m-auto p-2">
                        If you don't recieve an email, please make sure you've entered the address you registered with,
                        and check your spam folder.
                    </p>
                    <p class="m-auto p-2"><a href="{% url 'home'%}">Return to home page</a></p>
                </div>
        </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}

    

task/templates/task/account/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your account {{user.email}},
{{protocol}}://{{domain}}{% url 'password_reset_confirm' uidb64=uid token=token %}

if clicking the link above doesn't work,please copy and paste the URL in a new browser 
window instead.

Sincerely,
The Wetask Chat Team
{% endautoescape %}

task/templates/task/account/password_reset_form.html
{% extends 'base.html' %}
{% load static %}

{% block content%}

<form id="id_password_reset_form" method="POST" class="form-signin">{% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Reset password</h1>
    <input name="email" class="form-control" placeholder="Email address" type="email" id="id_email" required>
    <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block ">send reset email</button>

</form>

{% endblock content%}

task/templates/task/account/register.html
{% extends "task/base.html" %}
{% load static %}
{% block title %} 
register
{% endblock title %}

{% block content %}
<div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
data-sidebar-position="fixed" data-header-position="fixed">
<div
  class="position-relative overflow-hidden radial-gradient min-vh-100 d-flex align-items-center justify-content-center">
  <div class="d-flex align-items-center justify-content-center w-100">
    <div class="row justify-content-center w-100">
      <div class="col-md-8 col-lg-6 col-xxl-4">
        <div class="card mb-0">
          <div class="card-body">
            <p class="text-center">Wetask</p>
            <form method='post'>
              {% csrf_token %}
              <div class="mb-3">
                <label for="exampleInputtext1" class="form-label">Username</label>
                <input type="text" class="form-control" name='username' id="exampleInputtext1" aria-describedby="textHelp">
              </div>
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email Address</label>
                <input type="email" class="form-control" name='email' id="exampleInputEmail1" aria-describedby="emailHelp">
              </div>
              <div class="mb-4">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" name='password1' class="form-control" id="exampleInputPassword1">
              </div>
              <div class="mb-4">
                <label for="exampleInputPassword2" class="form-label"> confirm Password</label>
                <input type="password" name='password2' class="form-control" id="exampleInputPassword2">
              </div>
              <button class="btn btn-primary w-100 py-8 fs-4 mb-4 rounded-2">Sign Up</button>
              <div class="d-flex align-items-center justify-content-center">
                <p class="fs-4 mb-0 fw-bold">Already have an Account?</p>
                <a class="text-primary fw-bold ms-2" href="{% url 'login' %}">Sign In</a>
              </div>
            </form>
            {% if messages %}
            {% for message in messages %}
              {% if message.tag == error %}
              <p class="text-danger">{{message}}</p>
            {% endif %}
            {% endfor %}
        {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}

task/templates/task/account/reset_password.html
{% extends "task/base.html" %}
{% load static %}

{% block content %}
<div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
data-sidebar-position="fixed" data-header-position="fixed">
<div
  class="position-relative overflow-hidden radial-gradient min-vh-100 d-flex align-items-center justify-content-center">
  <div class="d-flex align-items-center justify-content-center w-100">
    <div class="row justify-content-center w-100">
      <div class="col-md-8 col-lg-6 col-xxl-4">
        <div class="card mb-0">
          <div class="card-body">
            <h1>Password reset</h1>
            <p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>
            <form method='post'>
                {% csrf_token %}
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email Address</label>
                <input type="email" class="form-control" name='email' id="exampleInputEmail1" aria-describedby="emailHelp">
              </div>
                <input type="submit" value="Reset my password" class="m-3 btn btn-primary">              
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}

task/templates/task/account/set_password.html
{% extends 'task/base.html' %}
{% load static %}
{% block content %}
<div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
data-sidebar-position="fixed" data-header-position="fixed">
<div
  class="position-relative overflow-hidden radial-gradient min-vh-100 d-flex align-items-center justify-content-center">
  <div class="d-flex align-items-center justify-content-center w-100">
    <div class="row justify-content-center w-100">
      <div class="col-md-8 col-lg-6 col-xxl-4">
        <div class="card mb-0">
          <div class="card-body">
            <h1> Create new Password</h1>
            <form method="post"><input type="hidden" name="csrfmiddlewaretoken" value="C8P80V40RCvOGTv9YJxvN93qQjBZZVcBxYOKoiubTUE7BseZcPJVoUrZVpRKzqjz">
                <fieldset class="module aligned">
                  <input class="hidden" autocomplete="username" value="admin@gmail.com" type='hidden'>
                  <div class="form-row field-password1">
                    
                    <div class="flex-container mb-3">
                      <label for="id_new_password1" class='form-label'>New password:</label>
                      <input type="password" class="form-control" name="new_password1" autocomplete="new-password" required="" aria-describedby="id_new_password1_helptext" id="id_new_password1">
                    </div>
                  </div>
                  <div class="form-row field-password2">
                    
                    <div class="flex-container mb-3">
                      <label for="id_new_password2" class='form-label'>Confirm password:</label>
                      <input type="password" class="form-control"  name="new_password2" autocomplete="new-password" required="" id="id_new_password2">
                    </div>
                  </div>
                </fieldset>
                <div class="submit-row">
                  <input type="submit" class='btn btn-primary' value="Change my password">
                </div>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

{% endblock content%}